---
- set_fact:
    template_dest: "{{ item.key }}"
    consul_config: "{{ item.value }}"

- name: Deploy Consul service configuration
  template:
    src: "{{ consul_config_src }}"
    dest: "{{ consul_config_dir}}/{{ template_dest }}.json"
    owner: "{{ consul_user_name }}"
    group: "{{ consul_group_name }}"
    validate: "{{ consul_user_home }}/bin/consul configtest -config-file %s"
